@startuml
left to right direction
skinparam packageStyle rectangle
:User: as user
rectangle Bot {
    usecase "Create Group" as cg
    usecase "Join Group" as ja
    usecase "Create Activity" as ca
    usecase "Check Status" as cs
    usecase "Participates" as pa
    usecase "List Activities" as la
}
user --> ca
user --> cg
user --> pa
user --> cs
user --> ja
user --> la
@enduml